import type { Database } from "@/lib/supabase/database.types";
import { ActionForm, ArticleCategoryFields, DeleteForm, SlugFields } from "./forms";
import { deleteArticle, deleteBook, saveArticle, saveBook, saveSettings } from "@/app/admin/actions";
type Article=Database["public"]["Tables"]["articles"]["Row"]; type Book=Database["public"]["Tables"]["books"]["Row"];
const local=(value:string|null)=>value?value.slice(0,16):"";
export function ArticleEditor({article}:{article?:Article}) { return <ActionForm action={saveArticle}>{article&&<input type="hidden" name="id" value={article.id}/>}<input type="hidden" name="existing_image" value={article?.hero_image_path??""}/><div className="form-grid"><SlugFields title={article?.title} slug={article?.slug}/><label>Status<select name="status" defaultValue={article?.status??"draft"}><option value="draft">Draft</option><option value="published">Published</option></select></label><ArticleCategoryFields category={article?.category} start={local(article?.event_start_at??null)} end={local(article?.event_end_at??null)} location={article?.event_location??""}/><label className="full">Excerpt<textarea name="excerpt" rows={3} defaultValue={article?.excerpt??""}/></label><label className="full">Body<textarea name="body" rows={12} defaultValue={article?.body??""}/></label><label>Hero image<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label>Published date<input name="published_at" type="datetime-local" defaultValue={local(article?.published_at??null)}/></label><label>Trending rank<input name="trending_rank" type="number" min="1" defaultValue={article?.trending_rank??""}/></label><label className="check"><input name="featured" type="checkbox" defaultChecked={article?.featured}/> Featured</label><label>SEO title<input name="seo_title" defaultValue={article?.seo_title??""}/></label><label className="full">SEO description<textarea name="seo_description" rows={3} defaultValue={article?.seo_description??""}/></label></div></ActionForm>; }
export function BookEditor({book}:{book?:Book}) { return <ActionForm action={saveBook}>{book&&<input type="hidden" name="id" value={book.id}/>}<input type="hidden" name="existing_image" value={book?.cover_image_path??""}/><div className="form-grid"><SlugFields title={book?.title} slug={book?.slug}/><label>Author<input name="author" required defaultValue={book?.author??""}/></label><label>Price (MYR)<input name="price" inputMode="decimal" required defaultValue={book?(book.price_cents/100).toFixed(2):""}/></label><label>Stock quantity<input name="stock_quantity" type="number" min="0" step="1" defaultValue={book?.stock_quantity??""}/></label><label>ISBN<input name="isbn" defaultValue={book?.isbn??""}/></label><label>Cover image<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label className="check"><input name="active" type="checkbox" defaultChecked={book?.active??true}/> Active</label><label className="check"><input name="featured" type="checkbox" defaultChecked={book?.featured}/> Featured</label><label className="full">Description<textarea name="description" rows={7} defaultValue={book?.description??""}/></label></div></ActionForm>; }
export function SettingsEditor({values}:{values:Record<string,unknown>}) { const contact=(values.contact??{}) as Record<string,string>,social=(values.social??{}) as Record<string,string>; return <ActionForm action={saveSettings}><div className="form-grid"><label className="full">Announcement text<input name="announcement" defaultValue={String(values.announcement??"")}/></label><label>Newsletter heading<input name="newsletterHeading" defaultValue={String(values.newsletterHeading??"")}/></label><label className="full">Newsletter copy<textarea name="newsletterCopy" rows={3} defaultValue={String(values.newsletterCopy??"")}/></label><label>Contact email<input name="contact_email" type="email" defaultValue={contact.email??""}/></label><label>Contact phone<input name="contact_phone" defaultValue={contact.phone??""}/></label><label>Instagram<input name="instagram" defaultValue={social.instagram??""}/></label><label>TikTok<input name="tiktok" defaultValue={social.tiktok??""}/></label><label>Facebook<input name="facebook" defaultValue={social.facebook??""}/></label></div></ActionForm>; }
export {DeleteForm,deleteArticle,deleteBook};
