import Link from "next/link";
import type { Article, ArticleCategory, Book } from "@/types/content";
import { categoryLabel } from "@/data/mock-data";
import { ArticleCard, Mark, PageShell } from "@/components/site";
import { formatMoney } from "@/lib/format";
import { AddToCart } from "@/components/cart/add-to-cart";

export function ArticleListing({ category, title, items }: { category?: ArticleCategory; title: string; items: Article[] }) {
  return <PageShell title={title} eyebrow={category ? categoryLabel[category] : "The latest"}><p className="page-intro">Stories, conversations and things worth knowing from Malaysia and beyond.</p>{items.length ? <div className="article-grid" style={{ marginTop: 50 }}>{items.map((article, index) => <ArticleCard key={article.id} article={article} lead={index === 0} />)}</div> : <div className="empty-state" style={{ marginTop: 50 }}><h2>Nothing here yet.</h2><p>New stories are on the way.</p></div>}</PageShell>;
}

export function StoryPage({ article }: { article: Article }) { return <PageShell title={article.title} eyebrow={categoryLabel[article.category]}><div className="book-detail"><Mark tone={article.image} /><div className="detail-copy"><p>{article.publishedAt}</p><p>{article.excerpt}</p>{article.body && <><h2>Read the story</h2><p>{article.body}</p></>}{article.category === "event" && <p><strong>{article.eventLocation}</strong>{article.eventStartAt && <> · {new Intl.DateTimeFormat("en-MY", { dateStyle: "medium", timeStyle: "short" }).format(new Date(article.eventStartAt))}</>}</p>}<Link className="button button-coral" href="/news">More stories</Link></div></div></PageShell>; }

export function BooksPage({ books }: { books: Book[] }) { return <PageShell title="Books we love" eyebrow="The bookstore, with opinions"><p className="page-intro">Books to take home, talk about and pass to someone you like.</p>{books.length ? <div className="book-list" style={{ marginTop: 50 }}>{books.map((book) => <Link className="book-card" href={`/books/${book.slug}`} key={book.id}><Mark tone={book.cover} /><h3>{book.title}</h3><p>{book.author}</p><strong>{formatMoney(book.priceCents, book.currency)}</strong></Link>)}</div> : <div className="empty-state" style={{ marginTop: 50 }}><h2>The shelf is being stocked.</h2><p>New books are on the way.</p></div>}</PageShell>; }

export function BookPage({ book }: { book: Book }) { return <PageShell title={book.title} eyebrow="Good reads"><div className="book-detail"><Mark tone={book.cover} /><div className="detail-copy"><p className="eyebrow">{book.author}</p><h2>{book.title}</h2><p>{book.description ?? "A carefully chosen title from the PEANUTZIN shelf."}</p><p className="book-price">{formatMoney(book.priceCents, book.currency)}</p>{book.stockQuantity !== null && book.stockQuantity !== undefined && <p>{book.stockQuantity > 0 ? `${book.stockQuantity} on the shelf` : "Currently out of stock"}</p>}<AddToCart bookId={book.id} slug={book.slug} disabled={book.stockQuantity===0}/></div></div></PageShell>; }

export function SimplePage({ title, eyebrow, copy }: { title: string; eyebrow?: string; copy: string }) { return <PageShell title={title} eyebrow={eyebrow}><div className="detail-copy"><p className="page-intro">{copy}</p><p>PEANUTZIN is an independent Malaysian book and media project. This Phase 1 shell is ready for real stories, community programmes and a growing shelf of books.</p></div></PageShell>; }

export function CartPage({ checkout = false }: { checkout?: boolean }) { return <PageShell title={checkout ? "Checkout" : "Your cart"} eyebrow={checkout ? "Almost there" : "A little shelf space"}><div className="empty-state"><h2>{checkout ? "Checkout is coming soon." : "Your cart is empty."}</h2><p>{checkout ? "This Phase 1 screen is a visual placeholder. No payment or order data is collected." : "Find something good to read, then come back here."}</p><Link className="button button-coral" href="/books">Browse books</Link></div></PageShell>; }

export function AdminPage({ section = "Dashboard" }: { section?: string }) { const metrics = [["Published articles", "128", "teal"], ["Books on shelf", "42", "coral"], ["Pending orders", "07", "yellow"], ["Social drafts", "16", "blue"]]; return <><div className="admin-layout"><aside><Link className="wordmark" href="/">PEANUTZIN<small>ADMIN STUDIO</small></Link>{["Dashboard", "Books", "Articles", "Orders", "Social Studio", "Settings"].map((item) => <Link className={section === item ? "active" : ""} href={item === "Dashboard" ? "/admin" : `/admin/${item.toLowerCase().replace(" ", "-")}`} key={item}>{item}</Link>)}</aside><main className="admin-main"><p className="eyebrow">Admin / {section}</p><h1>{section}</h1>{section === "Social Studio" ? <div className="workflow">{["Create", "AI Generate", "Review", "Edit", "Save", "Publish / Export"].map((item, index) => <div key={item}><strong>0{index + 1}</strong><span>{item}</span></div>)}</div> : <><div className="metrics">{metrics.map(([label, value, tone]) => <div className={`metric ${tone}`} key={label}><span>{label}</span><strong>{value}</strong><small>mock value</small></div>)}</div><div className="admin-panel"><h2>Recent activity</h2><p>All your publishing work in one calm place. Connect real content in Phase 2.</p></div></>}</main></div></>; }
