-- Editorial/demo inventory: original PEANUTZIN copy; factual items retain source URLs.
insert into public.articles(slug,title,excerpt,body,category,status,featured,trending_rank,hero_image_path,hero_image_alt,published_at,source_name,source_url) values
('how-dbp-manuscripts-move-from-submission-to-review','What happens after a manuscript reaches DBP?','A public submission guide offers a useful look at the first steps behind the editorial desk.','DBP’s published guidance says submitted manuscripts are registered and receive an initial assessment by the relevant editorial division. For emerging writers, the useful lesson is simple: presentation, originality declarations and a complete submission matter before the deeper editorial conversation begins.','news','published',false,null,'yellow','Typography-led artwork reading Manuscript to Editorial Desk','2026-08-27T10:00:00+08:00','Dewan Bahasa dan Pustaka','https://dbp.gov.my/panduan-penghantaran-karya-atau-manuskrip-ke-dewan-bahasa-dan-pustaka/'),
('gerakbudaya-and-the-case-for-alternative-shelves','Why alternative shelves matter to Malaysian reading culture','Gerakbudaya’s long-running mission shows how distribution can also be cultural work.','Gerakbudaya describes its work around socially aware books, alternative perspectives and hidden histories from Malaysia and the region. That framing is a reminder that a bookstore does more than move stock: it can make room for arguments, memories and writers that a mainstream shelf might miss.','news','published',false,null,'teal','Text-led collage of book spines and shelf labels','2026-08-24T10:00:00+08:00','Gerakbudaya','https://www.gerakbudaya.com/about-us'),
('dbp-training-keeps-language-publishing-skills-in-circulation','The classrooms behind Malaysia’s writing and publishing life','Akademi DBP’s remit connects language, literature and publishing through continuing education.','Akademi DBP says it develops training in language, literature and publishing for Malaysian and regional communities. The work sits behind the visible book: skills are shared, editors are developed and writers gain another place to practise their craft.','news','published',false,null,'coral','Bold editorial poster with the words Language Literature Publishing','2026-08-20T10:00:00+08:00','Akademi DBP','https://akademi.dbp.gov.my/mengenai'),
('the-tote-bag-has-entered-the-book-chat','The tote bag has entered the book chat','At fairs and launches, the unofficial uniform is practical, printed and full of new reading plans.','This is not an investigation. It is an affectionate field note: book people arrive carrying one bag and somehow leave needing two. The best examples become small travelling posters for presses, shops and reading communities.','gossip','published',false,null,'orange','Pop-art tote bag with books and oversized lettering','2026-08-26T09:00:00+08:00',null,null),
('are-readers-choosing-mood-before-genre','Are readers choosing mood before genre?','The recommendation question increasingly sounds like: what kind of evening are you having?','Genre still matters, but reader conversations often begin elsewhere: short or sprawling, comforting or unsettling, quiet or impossible to put down. For booksellers, that language opens playful routes into unfamiliar local work.','gossip','published',false,null,'blue','Colour blocks labelled quiet strange tender loud','2026-08-23T09:00:00+08:00',null,null),
('the-return-of-the-annotated-copy','The annotated copy is back in public','Tabs, pencil marks and marginal arguments are becoming part of how readers share a book.','A pristine book has its pleasures, but visibly read copies carry another energy. Notes show where a sentence stopped someone. Tabs turn private attention into a map that friends can follow. The conversation continues on the page.','gossip','published',false,null,'yellow','Collage of paper tabs and handwritten marginal marks','2026-08-18T09:00:00+08:00',null,null),
('small-press-covers-are-doing-the-talking','Small-press covers are doing the talking','A sharp title and one fearless colour can travel farther than a polished campaign.','Independent books often announce themselves with economy: type, paper, one surprising image. On a crowded table, that clarity can become an invitation. Readers notice when a cover feels like part of the editorial idea.','gossip','published',false,null,'teal','Grid of fictional geometric cover studies without readable titles','2026-08-13T09:00:00+08:00',null,null),
('why-bilingual-reading-lists-feel-like-home','Why bilingual reading lists feel like home','Moving between Bahasa Melayu and English can widen the conversation rather than split it.','Many Malaysian readers live between languages every day. A bilingual reading life can hold different rhythms, humour and histories at once. The interesting shelf is not arranged as a contest; it lets books speak across the aisle.','feature','published',true,null,'coral','Two-column typographic artwork in warm cream and orange','2026-08-25T11:00:00+08:00',null,null),
('a-field-guide-to-your-first-independent-book-fair','A field guide to your first independent book fair','Come curious, leave space in the bag and ask the person behind the table what they are excited about.','Small fairs reward wandering. Begin with the tables you do not recognise, read a first page and talk to publishers about the risks they took. A modest budget and an open afternoon can produce a wonderfully strange reading list.','feature','published',false,null,'yellow','Map-like poster of tables arrows and book stacks','2026-08-21T11:00:00+08:00',null,null),
('the-quiet-infrastructure-of-a-reading-community','The quiet infrastructure of a reading community','Before the packed launch, there are librarians, booksellers, editors and volunteers making the room possible.','Literary culture is built through repeated acts of care: setting chairs, circulating a poster, recommending one precise title and welcoming the person who came alone. The visible event is only the bright edge of that work.','feature','published',false,null,'blue','Editorial diagram linking library bookshop reader and writer','2026-08-16T11:00:00+08:00',null,null),
('childrens-books-deserve-serious-design','Children’s books deserve serious design','Young readers notice rhythm, colour, paper and the exact distance between image and word.','Design for children is not simplified adult design. It asks how a page invites attention, how an illustration carries narrative and how a physical object survives rereading. The best books trust young readers with visual intelligence.','feature','published',false,null,'teal','Playful geometric page shapes in PEANUTZIN colours','2026-08-11T11:00:00+08:00',null,null),
('ebooks-and-the-shape-of-a-local-backlist','eBooks can give a local backlist another life','Digital formats are most useful when they expand access without weakening the value of the work.','An eBook edition can reach readers who are far from a particular shop or fair. The publishing challenge is not merely exporting a file: pricing, rights, typography and protected delivery all deserve the same editorial attention as print.','feature','published',false,null,'orange','Book page transforming into clean digital blocks','2026-08-07T11:00:00+08:00',null,null),
('how-to-read-a-book-fair-programme','How to read a book-fair programme without exhausting yourself','Choose one anchor conversation, one unfamiliar table and enough empty time to be surprised.','A fair can make every hour look essential. It rarely is. Build the day around one event you care about, then leave room for browsing, food and the conversation that was never printed in the programme.','news','published',false,null,'pink','Folded programme with circles arrows and one highlighted session','2026-08-09T10:00:00+08:00',null,null),
('podcasts-are-becoming-the-reading-list-before-the-reading-list','The podcast is becoming the reading list before the reading list','A good books conversation can create curiosity before a reader meets the first page.','Audio gives books room to travel through commutes, kitchens and late-night walks. The strongest literary podcasts do not replace reading; they make an inviting doorway into context, craft and unfamiliar voices.','news','published',false,null,'blue','Microphone beside stacked books in a paper collage','2026-08-05T10:00:00+08:00',null,null),
('what-a-local-voices-shelf-can-do','What a Local Voices shelf can do','A collection label becomes useful when it leads to genuine range rather than a single idea of Malaysia.','Local writing includes many languages, forms, regions, generations and publishing routes. A thoughtful shelf keeps that variety visible and makes discovery easier without pretending that one label can explain every book.','news','published',false,null,'coral','Typographic shelf labels layered like a street poster','2026-08-03T10:00:00+08:00',null,null)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,status=excluded.status,featured=excluded.featured,hero_image_path=excluded.hero_image_path,hero_image_alt=excluded.hero_image_alt,published_at=excluded.published_at,source_name=excluded.source_name,source_url=excluded.source_url;

-- Third-party records are preview-only and do not imply a supply relationship.
insert into public.books(slug,title,author,description,price_cents,currency,cover_image_path,featured,active,stock_quantity,publisher,language,genre,format,ebook_price_cents,catalogue_type,independent_publisher,emerging_author,preview_only) values
('the-sum-of-our-follies','The Sum of Our Follies','Shih-Li Kow','A Malaysian novel selected for the preview shelf.',5900,'MYR','yellow',true,true,6,'Silverfish Books','English','Literary fiction','physical',null,'independent_publisher',true,false,true),
('lake-like-a-mirror','Lake Like a Mirror','Soo Thong Kwan','Short fiction from a distinctive Malaysian voice.',5200,'MYR','teal',false,true,5,'Silverfish Books','English','Short stories','physical',null,'independent_publisher',true,false,true),
('the-weight-of-our-sky','The Weight of Our Sky','Hanna Alkaf','Young adult historical fiction by a Malaysian author.',5500,'MYR','coral',true,true,8,'Salaam Reads','English','Young adult','both',3200,'indie_author',false,false,true),
('the-garden-of-evening-mists','The Garden of Evening Mists','Tan Twan Eng','Literary fiction by a Malaysian novelist.',6200,'MYR','blue',false,true,4,'Canongate','English','Literary fiction','ebook',3900,'indie_author',false,false,true),
('we-children-from-bahnhof-zoo-malaysian-edition','KL Noir: Red','Various authors','An anthology associated with Malaysian urban writing.',4800,'MYR','orange',false,true,7,'Buku Fixi','English','Anthology','physical',null,'independent_publisher',true,false,true),
('black-water-sister','Black Water Sister','Zen Cho','Contemporary fantasy by a Malaysian author.',3500,'MYR','pink',false,true,10,null,'English','Fantasy','ebook',2200,'indie_author',false,false,true),
('the-accidental-malay','The Accidental Malay','Karina Robles Bahrin','Contemporary Malaysian fiction on the preview shelf.',5800,'MYR','yellow',false,true,5,'Epigram Books','English','Literary fiction','both',3500,'indie_author',true,false,true),
('the-cats-we-meet-along-the-way','The Cats We Meet Along the Way','Nadia Mikail','Young adult fiction by a Malaysian author.',4200,'MYR','teal',false,true,9,null,'English','Young adult','physical',null,'indie_author',false,true,true),
('the-ghost-bride','The Ghost Bride','Yangsze Choo','Historical fantasy by a Malaysian author.',5000,'MYR','coral',false,true,null,null,'English','Historical fantasy','ebook',3000,'indie_author',false,false,true),
('new-malaysian-essays','New Malaysian Essays','Various authors','A preview route into Malaysian independent nonfiction.',4500,'MYR','blue',false,true,6,'Matahari Books','English','Essays','physical',null,'independent_publisher',true,false,true)
on conflict(slug) do update set title=excluded.title,author=excluded.author,description=excluded.description,price_cents=excluded.price_cents,publisher=excluded.publisher,language=excluded.language,genre=excluded.genre,format=excluded.format,ebook_price_cents=excluded.ebook_price_cents,catalogue_type=excluded.catalogue_type,independent_publisher=excluded.independent_publisher,emerging_author=excluded.emerging_author,preview_only=excluded.preview_only;
