"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/admin/auth";
import { createClient } from "@/lib/supabase/server";
import { AI_CONFIG } from "@/lib/ai/config";
import { generateSocial, type SocialPlatform } from "@/lib/ai/social";
export type StudioState={error?:string;success?:string;id?:string;generated?:Record<string,string>;platform?:SocialPlatform;model?:string;generatedAt?:string};
const statuses=["draft","generated","reviewed","ready"] as const;
const text=(form:FormData,key:string,max:number)=>String(form.get(key)??"").trim().slice(0,max);
const nullable=(form:FormData,key:string,max:number)=>text(form,key,max)||null;
const generatedFields=(x:Awaited<ReturnType<typeof generateSocial>>["content"])=>({facebook_copy:x.facebook,instagram_copy:x.instagram,linkedin_copy:x.linkedin,threads_copy:x.threads,short_copy:x.shortCopy,hashtags:x.hashtags.map(h=>h.startsWith("#")?h:`#${h}`).join(" "),seo_title:x.seoTitle,seo_description:x.seoDescription});
function draftValues(form:FormData){const status=String(form.get("status")??"draft"),raw=text(form,"generation_metadata",1000);let generation_metadata:Record<string,string>={};try{generation_metadata=raw?JSON.parse(raw):{};}catch{/* Discard invalid audit metadata. */}return {source_article_id:nullable(form,"source_article_id",36),title:text(form,"title",160),master_brief:text(form,"master_brief",AI_CONFIG.maxBriefChars),tone_notes:nullable(form,"tone_notes",AI_CONFIG.maxToneChars),facebook_copy:nullable(form,"facebook_copy",5000),instagram_copy:nullable(form,"instagram_copy",5000),linkedin_copy:nullable(form,"linkedin_copy",5000),threads_copy:nullable(form,"threads_copy",1000),short_copy:nullable(form,"short_copy",1000),hashtags:nullable(form,"hashtags",1000),seo_title:nullable(form,"seo_title",160),seo_description:nullable(form,"seo_description",320),status:(statuses.includes(status as typeof statuses[number])?status:"draft") as typeof statuses[number],generation_model:nullable(form,"generation_model",100),generation_metadata};}
export async function saveSocialDraft(_previous:StudioState,form:FormData):Promise<StudioState>{const admin=await requireAdmin(),values=draftValues(form),id=nullable(form,"id",36);if(!values.title)return{error:"Add a draft title."};if(values.master_brief.length<20)return{error:"The master brief must be at least 20 characters."};const supabase=await createClient();if(values.source_article_id){const {data}=await supabase.from("articles").select("id").eq("id",values.source_article_id).maybeSingle();if(!data)return{error:"The selected source article is no longer available."};}const result=id?await supabase.from("social_drafts").update(values).eq("id",id).select("id").single():await supabase.from("social_drafts").insert({...values,created_by:admin.id}).select("id").single();if(result.error)return{error:"The social draft could not be saved."};revalidatePath("/admin/social-studio");return{success:"Draft saved.",id:result.data.id};}
export async function generateSocialCopy(_previous:StudioState,form:FormData):Promise<StudioState>{await requireAdmin();const values=draftValues(form),platform=String(form.get("platform")??"all") as SocialPlatform;if(values.master_brief.length<20)return{error:"Add a master brief of at least 20 characters before generating."};if(!["all","facebook","instagram","linkedin","threads","shortCopy","hashtags","seoTitle","seoDescription"].includes(platform))return{error:"Invalid generation target."};const supabase=await createClient();let article:string|undefined;if(values.source_article_id){const {data}=await supabase.from("articles").select("title,excerpt,body,category,event_start_at,event_end_at,event_location").eq("id",values.source_article_id).maybeSingle();if(!data)return{error:"The selected source article is no longer available."};article=[`Title: ${data.title}`,`Category: ${data.category}`,data.excerpt&&`Excerpt: ${data.excerpt}`,data.body&&`Body: ${data.body.slice(0,AI_CONFIG.maxArticleChars)}`,data.event_start_at&&`Event start: ${data.event_start_at}`,data.event_end_at&&`Event end: ${data.event_end_at}`,data.event_location&&`Event location: ${data.event_location}`].filter(Boolean).join("\n");}try{const result=await generateSocial({brief:values.master_brief,toneNotes:values.tone_notes??undefined,article,platform});return{success:"Copy generated. Review and save your edits.",generated:generatedFields(result.content),platform,model:result.model,generatedAt:new Date().toISOString(),id:nullable(form,"id",36)??undefined};}catch(error){return{error:error instanceof Error?error.message:"AI generation failed. Your edits are safe."};}}
export async function deleteSocialDraft(form:FormData){await requireAdmin();const id=text(form,"id",36);if(id){const {error}=await(await createClient()).from("social_drafts").delete().eq("id",id);if(error)throw new Error("The social draft could not be deleted.");}revalidatePath("/admin/social-studio");}
